### ISSUE TITLE
在線検知機能

### ISSUE THREAD

**Issue by nona-takahara** [nona-takahara/n-tracs-core-for-stormworks#2]
イレギュラーな車両への対応のため、ゲージを使った位置情報転送に対応することとなりました。以下のように設計してあります。

### ゲージがない車両
ボクセル引数を渡さない場合の`server.getVehiclePos`が返す位置を、位置検出ペインタブルブロック2個以上の中心点 または 1個目の位置とみなすように処理します。

### ゲージがある車両
位置検出ペインタブルブロックの名前に`_POS`を付加したゲージのprimary valueをGPSが返すX座標、secondary valueをGPSが返すY座標（アドオンZ座標）とするように処理します。

## エリア検出
エリアを判定する。前回居た地点をスタートとする幅優先探索を行うことを推奨します。v0.1.0もその処理です。

各検出位置はエリア内でどのような順序であるか（どれが最も左・最も右であるか）判別可能になるよう設計してください（ATC情報の送信で必要になります）。

エリアでは上り線フラグ・下り線フラグを付け外ししています（エリアの頂点数を節約するための処置）。

- 上りフラグ設定エリアでは、上りフラグを立てて下りフラグを外し、上り線と判定する
- 下りフラグ設定エリアでは、下りフラグを立てて上りフラグを外し、下り線と判定する
- エリアが上りと下りで違う抽象軌道回路を構成している場合は、フラグを操作せず、以前ついた状態で上下線を判別する
- エリアが上り下りともに同じ抽象軌道回路を構成している場合は、うまく処理する

**Comment by nona-takahara** [comment]
エリア内外の判定コードがMITじゃなかったのに消し忘れたという大失態をしました……

**Comment by nona-takahara** [comment]
エリア内外の判定コードがMITライセンスや互換性のあるライセンスじゃなかったのに消し忘れたという大失態をしました……
こういう場合の対処法を良く知らないのですが、今回は事前の根回しの甲斐あって、すでに作ってあった全く別のアルゴリズムによるコードに差し替えます

**Comment by Teinishi** [comment]
`Axle.search` に関して、現在は幅優先探索のために各Areaに足跡をつける実装になっていますが、これをキューに追加するときに重複を確認する実装に変更します。これに伴い、`Area` から `bfsFootmark` のフィールドを削除することになります。`Area` のコンストラクタがどこにあるか、そもそも存在するのかわかりませんが、もしあるならそちらの変更も必要になるかと思います。

`Area` のフィールドの変更といえば、#3 にあるように `minX`、`maxX`、`minZ`、`maxZ` (仮、`boundingBox` とかでもよさそう)を追加し、同時に `Area.isInArea` も変更したいと思っています。この変更についても `Area` のコンストラクタの変更が伴うと思います。

**Comment by nona-takahara** [comment]
~~Areaは、`src/n_tracs_soyabridge/axle.lua`にコンストラクタがあります。~~
幅優先探索のノードづくりの関係で、`overWrite`が必要かもしれないので、 #8 やCoreの実装を参考に、ついでに追加してOKです（厳密にIssue切ってるわけではないので、ある程度融通利かせてしまってください）。

**Comment by Teinishi** [comment]
幅優先探索の実装の変更に着手しました。 feature-renew-axle-search ブランチで作業しています。
Area のコンストラクタと言ったのは `Area.new` がどこかにあるのではないかということだったのですが、`axle.lua` には見つからず (もし本当にここにあったら困っちゃうけど)、今回は `bfsFootmark` の削除が目的だったので今のところはこの名前で全文検索かけて見つかったファイルを変更しています。
おそらく、このリポジトリの外で宣言されるであろう `DEFAULT_AREA` や `AREAS` に Area のインスタンスが来ることと思いますが、私からはこれらに手を付けることができないので少々心配になっています。まだそちらを作っていないのであれば安心できますが。

**Comment by nona-takahara** [comment]
見間違いをしました。`Area.new`はまだどこにもありません。同時に作業をしていないので、問題ないです

**Comment by nona-takahara** [comment]
一旦 #3 の作業を進めて、実装に問題がないかチェックしたいところですかね……

作業が遅くてすみません。

**Comment by nona-takahara** [comment]
今後このIssueは問題が発生しなければ追記することがないので、一旦クローズします。
