### ISSUE TITLE
エリア・抽象軌道回路のデータ構造

### ISSUE THREAD

**Issue by nona-takahara** [nona-takahara/n-tracs-core-for-stormworks#3]
[nona-takahara/storm-n-tracs-editor](https://github.com/nona-takahara/storm-n-tracs-editor)で開発しているエディタが吐き出すデータに基づいてエリア・抽象軌道回路データを生成します。

この吐き出すデータ形式について、現状は以下のようになっていますが、これの改善案を考えます。
```js
{
  "vertex": [
    {"x": 0, "z": 1},
   // ...
  ],
  "polygons": [
    {
      "name": "Area1",
      "vertexId": [0, 2, 1],
      "rawVertex": [{"x": 0, "z": 1}, /*...*/ ],
      "related": ["Area2", "Area3", "Area4"],
      "downTrack": "21T",
      "upTrack": "",
      "leftIndex": 1,
      "rightIndex": 2
    },
    // ...
  ],
  "addons": [
    // Stormworks Addon Path
  ]
}
```

現状の問題点
- 必要なデータに対して書かれているデータが冗長だったり不足していたり、項目名の説明が悪い
- `downTrack`や`upTrack`の文字列に依存している情報が**実は**ある

**Comment by Teinishi** [comment]
`rawVertex` に座標値を埋め込んでしまうなら、同時にX、Zそれぞれの最小値、最大値のフィールドもあるといいかもしれません。点の内外判定のとき、バウンディングボックス的な感じで明らかに外れている点ならスキップできるとちょっと軽量化できそう。

**Comment by nona-takahara** [comment]
座標値が埋め込まれてるのも実は現行版では使ってないので、頂点を別テーブルにするか、ポリゴンテーブル内に収めるかのどちらか片方にするのが筋かなと思います。
本来なら実装しやすい方としたいのですが、なんだかんだ上限がある文字数と戦うポイントではある（特にCS-ATC版ではポリゴン数が増えやすい）ので、自動圧縮が効きやすい気がする別テーブルに絞るのはどうでしょうか。

**Comment by Teinishi** [comment]
別テーブルに絞るのはいいと思います。その場合 `Area` 構造体に `minX`、`minZ`、`maxX`、`maxZ` みたいなフィールドがあると嬉しいです。

**Comment by nona-takahara** [comment]
jsonファイルの方には用意しなくても、ビルド時、なんなら実行時に持たせてあげれば十分かなと思います。
たぶん実行時に持たせるのが一番文字数削るのに効きそう。

**Comment by nona-takahara** [comment]
改良案です

頂点と、エリア（頂点情報、検索用情報、フラグ情報）、抽象軌道回路（エリアとフラグのセット情報）を持たせてあげるという提案です。

```js
{
  "vertexes": [
    {"x": 0, "z": 1},
    // ...
  ],
  "areas": [
    {
      "name": "Area1",
      "vertexId": [0, 2, 1],                  // 上のvertexのindex。反時計回り
      "leftVertexId": 2,                      // 上のvertexのindexで指定
      "related": ["Area2", "Area3", "Area4"], // 幅優先探索で見に行くべきお隣さん
      "trackFlag": "upbound"                  // | "downbound" | "none"
    },
    // ...
  ],
  "tracks": [
    {
      "name": "21T",
      "areas": [ // 左から順に記載
        { "name": "Area1", "trackFlag": "none" },
        { "name": "Area3", "trackFlag": "downbound" }
      ]
    },
    // ...
  ],
  "addons": [
    // Stormworks Addon Path
  ]
}
```

**Comment by Teinishi** [comment]
実行時に持たせるの、いいと思います。抽象軌道回路はまだよくわかってないのでなんとも。

**Comment by nona-takahara** [comment]
OK. おそらくデータ構造はこれで一応は問題ないと思います
マージするまではIssueは開けたままにします

**Comment by nona-takahara** [comment]
このIssueは、元データにとどまらず、データ構造全般を扱う方針にします

Areaの負担する機能が多すぎて苦労しそうです
- Axleの上下フラグによって、Area内の順番情報をupAxle・downAxleの片方または両方を設定する必要あり
- 軌道回路を介して送信する情報の設定はAreaのコールバックとしたい（確実な伝送のためには、直接関連のあるTrack・Leverや、隣のAreaのAxleの有無情報を見に行く必要もあり、厄介）
- （なお、Trackは自分に関連のあるAreaのAxleの有無を見るだけでisShortが確定する）

**Comment by nona-takahara** [comment]
とりあえず、Area・Axleについては、必要な機能とフィールドとメソッドを確定させてから実装に取り掛かるべきだと思っています

**Comment by nona-takahara** [comment]
思い出したように連投していてすみません

Lever, Switch, Track, Areaは全てユニークな名前を当てて、それを使って呼びだせるようにするので、その機構をBridgeの中で用意してあげる必要がありそうです。

また、それらの定義の際に入れ子になることがあるので、未定義の場合は空参照を作っておいて、後から呼べるようにする必要もあります。

**Comment by nona-takahara** [comment]
大変長らくお待たせいたしました。
データ構造について、連想配列型と一般の配列型どちらを採用すると変換プログラムが実装しやすいか意見を伺いに参りました
```json
{
  "vertexes": {
    "v1": { "x": 10, "z": 15 },
    "v2": { "x": 13, "z": 14 }
  }
}
```
か
```json
{
  "vertexes": [
    { "name": "v1", "x": 10, "z": 15 },
    { "name": "v2", "x": 13, "z": 14 }
  ]
}
```
かの違いです

**Comment by nona-takahara** [comment]
配列型を採用しました

**Comment by nona-takahara** [comment]
`res/area_track.json`にファイルを配置します

**Comment by nona-takahara** [comment]
storm-n-tracs-editor側の作業が完了しました。最終的な形式は以下のようになりました。
```
{
  "vertexes": [
    {"name": "v1", "x": 0, "z": 1},
    // ...
  ],
  "areas": [
    {
      "name": "Area1",
      "vertexId": [0, 2, 1],                  // 上のvertexのindex。反時計回り
      "leftVertexId": 2,                      // 上のvertexのindexで指定
      "related": ["Area2", "Area3", "Area4"], // 幅優先探索で見に行くべきお隣さん
      "trackFlag": "upbound"                  // | "downbound" | "none"
    },
    // ...
  ],
  "tracks": [
    {
      "name": "21T",
      "areas": [ // 左から順に記載
        { "name": "Area1", "trackFlag": "none" },
        { "name": "Area3", "trackFlag": "downbound" }
      ]
    },
    // ...
  ],
  "addons": [
    // Stormworks Addon Path
  ]
}
```

**Comment by nona-takahara** [comment]
実装の正当性の検証負荷が高くなる上下線フラグは外します

**Comment by nona-takahara** [comment]
一応実装したのでクローズします
